server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: us-east-1
  s3:
    buckets:
      customer: amigoscode-customer

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  codec:
    max-in-memory-size: 5MB
